# Generated by Django 5.2.9 on 2026-01-20 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_scheduling_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("install", "Install"),
                            ("uninstall", "Uninstall"),
                            ("bulk_install", "Bulk Install"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "package_spec",
                    models.CharField(
                        help_text="Package specification (e.g., 'requests==2.31.0') or requirements content for bulk install",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("output", models.TextField(blank=True, help_text="pip stdout")),
                ("error", models.TextField(blank=True, help_text="pip stderr")),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="django-q2 task ID for tracking",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_operations",
                        to="core.environment",
                    ),
                ),
            ],
            options={
                "verbose_name": "package operation",
                "verbose_name_plural": "package operations",
                "db_table": "package_operations",
                "ordering": ["-created_at"],
            },
        ),
    ]
