# Generated by Django 5.2.9 on 2026-01-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="webhook_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique token for webhook URL (auto-generated)",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
