# Generated by Django 5.2.9 on 2026-01-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_webhook_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="default_notification_email",
            field=models.EmailField(
                blank=True,
                help_text="Default email address for all notifications",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="email_backend",
            field=models.CharField(
                choices=[
                    ("disabled", "Disabled"),
                    ("smtp", "SMTP"),
                    ("resend", "Resend API"),
                ],
                default="disabled",
                help_text="Email backend for notifications",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="resend_api_key_encrypted",
            field=models.TextField(blank=True, help_text="Resend API key (encrypted)"),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="resend_from_email",
            field=models.EmailField(
                blank=True, help_text="From email address for Resend", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="smtp_from_email",
            field=models.EmailField(
                blank=True, help_text="From email address for SMTP", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="smtp_host",
            field=models.CharField(
                blank=True, help_text="SMTP server hostname", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="smtp_password_encrypted",
            field=models.TextField(blank=True, help_text="SMTP password (encrypted)"),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="smtp_port",
            field=models.PositiveIntegerField(
                default=587, help_text="SMTP server port"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="smtp_use_tls",
            field=models.BooleanField(
                default=True, help_text="Use TLS for SMTP connection"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="smtp_username",
            field=models.CharField(
                blank=True, help_text="SMTP username", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="notify_email",
            field=models.EmailField(
                blank=True,
                help_text="Override email for this script (uses global default if empty)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="notify_on",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("failure", "On Failure"),
                    ("success", "On Success"),
                    ("both", "On Success and Failure"),
                ],
                default="never",
                help_text="When to send notifications for this script",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="notify_webhook_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable webhook notifications for this script"
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="notify_webhook_url",
            field=models.URLField(
                blank=True,
                help_text="URL to POST notification webhooks to",
                max_length=500,
            ),
        ),
    ]
