# Generated by Django 5.2.9 on 2026-01-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_notification_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="auto_cleanup_enabled",
            field=models.BooleanField(
                default=False, help_text="Automatically clean up old runs daily"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("YYYY-MM-DD", "YYYY-MM-DD (ISO)"),
                    ("MM/DD/YYYY", "MM/DD/YYYY (US)"),
                    ("DD/MM/YYYY", "DD/MM/YYYY (EU)"),
                    ("DD.MM.YYYY", "DD.MM.YYYY"),
                ],
                default="YYYY-MM-DD",
                help_text="Date display format",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="instance_name",
            field=models.CharField(
                blank=True,
                default="PyRunner",
                help_text="Instance name displayed in header and emails",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="last_cleanup_at",
            field=models.DateTimeField(
                blank=True, help_text="When the last cleanup was performed", null=True
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="retention_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Keep last X runs per script (0 = unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="retention_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Delete runs older than X days (0 = keep forever)"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="time_format",
            field=models.CharField(
                choices=[("24h", "24-hour"), ("12h", "12-hour")],
                default="24h",
                help_text="Time display format",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="Default timezone for the instance",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="retention_count_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Override global retention count for this script",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="retention_days_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Override global retention days for this script",
                null=True,
            ),
        ),
    ]
