# Generated by Django 5.2.9 on 2026-01-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_phase7_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="worker_heartbeat_at",
            field=models.DateTimeField(
                blank=True, help_text="Last heartbeat from django-q workers", null=True
            ),
        ),
    ]
