# Generated by Django 5.2.9 on 2026-01-24 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_worker_heartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this script was archived (null = not archived)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_scripts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
