# Generated by Django 5.2.9 on 2026-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_script_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="setup_completed",
            field=models.BooleanField(
                default=False, help_text="Whether initial setup has been completed"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="setup_completed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the initial setup was completed", null=True
            ),
        ),
    ]
