# Generated by Django 5.2.9 on 2026-01-24 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_registration_and_invites"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "password reset token",
                "verbose_name_plural": "password reset tokens",
                "db_table": "password_reset_tokens",
            },
        ),
        migrations.RenameIndex(
            model_name="userinvite",
            new_name="user_invite_token_e617ee_idx",
            old_name="user_invite_token_idx",
        ),
        migrations.RenameIndex(
            model_name="userinvite",
            new_name="user_invite_email_cf6347_idx",
            old_name="user_invite_email_idx",
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["token", "expires_at"], name="password_re_token_9adc88_idx"
            ),
        ),
    ]
