# Generated by Django 5.2.9 on 2026-01-24 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_password_reset_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name (must be unique)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("gray", "Gray"),
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("pink", "Pink"),
                        ],
                        default="gray",
                        help_text="Tag color for visual distinction",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="script",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags for organizing and filtering scripts",
                related_name="scripts",
                to="core.tag",
            ),
        ),
    ]
