# Generated by Django 5.2.9 on 2026-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="q_queue_limit",
            field=models.PositiveIntegerField(
                default=20, help_text="Maximum number of tasks in the queue"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="q_retry",
            field=models.PositiveIntegerField(
                default=660, help_text="Seconds before a task is retried after timeout"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="q_timeout",
            field=models.PositiveIntegerField(
                default=600, help_text="Task timeout in seconds (0 for no timeout)"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="q_workers",
            field=models.PositiveIntegerField(
                default=2, help_text="Number of worker processes for task queue"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="worker_settings_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When worker settings were last updated (requires restart)",
                null=True,
            ),
        ),
    ]
