# Generated by Django 5.2.9 on 2026-01-24 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_worker_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this data store (used in scripts)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this data store is used for",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_datastores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "data store",
                "verbose_name_plural": "data stores",
                "db_table": "datastores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataStoreEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique key within this data store", max_length=255
                    ),
                ),
                ("value_json", models.TextField(help_text="JSON-encoded value")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "datastore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.datastore",
                    ),
                ),
            ],
            options={
                "verbose_name": "data store entry",
                "verbose_name_plural": "data store entries",
                "db_table": "datastore_entries",
                "ordering": ["key"],
                "indexes": [
                    models.Index(
                        fields=["datastore", "key"],
                        name="datastore_e_datasto_6e5232_idx",
                    )
                ],
                "unique_together": {("datastore", "key")},
            },
        ),
    ]
