# Generated by Django 6.0.1 on 2026-06-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_field_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="claude_api_key_encrypted",
            field=models.TextField(
                blank=True, help_text="Anthropic API key (encrypted)"
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="claude_auth_method",
            field=models.CharField(
                choices=[
                    ("subscription", "Claude subscription (OAuth token)"),
                    ("api_key", "Anthropic API key"),
                ],
                default="subscription",
                help_text="Authenticate with a Claude subscription token or an Anthropic API key",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="claude_default_model",
            field=models.CharField(
                blank=True,
                help_text="Optional default model id (e.g. claude-sonnet-4-6). Blank = account default.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="claude_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Make Claude AI available to scripts (via the pyrunner_ai helper)",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="claude_last_tested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Claude connection was last successfully tested",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="claude_oauth_token_encrypted",
            field=models.TextField(
                blank=True,
                help_text="Claude Code OAuth token from `claude setup-token` (encrypted)",
            ),
        ),
    ]
