# Generated by Django 6.0.1 on 2026-06-14 03:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_claude_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaudeUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("script_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("run_id", models.UUIDField(blank=True, null=True)),
                ("script_name", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("script", "Script"), ("test", "Test")],
                        default="script",
                        max_length=10,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cache_creation_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("num_turns", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("cost_usd", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Claude usage",
                "verbose_name_plural": "Claude usage",
                "db_table": "claude_usage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="claude_usag_created_8b6c6c_idx"
                    )
                ],
            },
        ),
    ]
