# Generated by Django 6.0.1 on 2026-06-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_recaptcha_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="update_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the update check last ran successfully",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="update_latest_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Latest PyRunner version seen on GitHub (populated by the update check)",
                max_length=50,
            ),
        ),
    ]
