# Generated by Django 6.0.1 on 2026-06-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_globalsettings_update_checked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="pid",
            field=models.IntegerField(
                blank=True,
                help_text="OS PID of the running script subprocess (for kill).",
                null=True,
            ),
        ),
    ]
