# Generated by Django 6.0.1 on 2026-07-15 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_api_token_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginPublicPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Capability token routing /p/<token>/ (auto-generated).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("plugin_slug", models.CharField(db_index=True, max_length=100)),
                ("page", models.CharField(max_length=100)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Revoked pages 404; re-sharing rotates the token.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiry. An expired link 404s and never comes back.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_public_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        help_text="Workspace whose data the page renders (share dies with it).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_public_pages",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "plugin public page",
                "verbose_name_plural": "plugin public pages",
                "db_table": "plugin_public_pages",
                "ordering": ["plugin_slug", "page"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plugin_slug", "page", "workspace"),
                        name="uniq_public_page_per_ws",
                    )
                ],
            },
        ),
    ]
