# Generated by Django 6.0.1 on 2026-07-16 09:34

import django.core.validators
import django.db.models.deletion
import re
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_plugin_public_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="library_versions",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Library revisions pinned at queue time: {library_key: version}.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Python import name for this library (e.g. 'gmail_agent_lib').",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Key must be a valid Python module name: lowercase letter first, then lowercase letters, digits or underscores (e.g. 'gmail_agent_lib').",
                                regex=re.compile("^[a-z][a-z0-9_]*$"),
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "owner_plugin",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Slug of the plugin that owns this library (NULL = user-created).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "owner_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stable per-owner handle for idempotent upsert (NULL = unmanaged).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "current_version",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Version number of the head revision (0 = no content yet).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_libraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workspace this resource belongs to (tenancy seam; nullable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="libraries",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "library",
                "verbose_name_plural": "libraries",
                "db_table": "libraries",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="LibraryRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "modules",
                    models.JSONField(
                        default=dict,
                        help_text="Module map {filename: code} for this revision.",
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_library_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="core.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "library revision",
                "verbose_name_plural": "library revisions",
                "db_table": "library_revisions",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ScriptLibrary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.library",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_attachments",
                        to="core.script",
                    ),
                ),
            ],
            options={
                "verbose_name": "script library",
                "verbose_name_plural": "script libraries",
                "db_table": "script_libraries",
            },
        ),
        migrations.AddField(
            model_name="script",
            name="libraries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Libraries this script can import at run time.",
                related_name="attached_scripts",
                through="core.ScriptLibrary",
                through_fields=("script", "library"),
                to="core.library",
            ),
        ),
        migrations.AddConstraint(
            model_name="library",
            constraint=models.UniqueConstraint(
                fields=("workspace", "key"), name="uniq_library_workspace_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="library",
            constraint=models.UniqueConstraint(
                condition=models.Q(("workspace__isnull", True)),
                fields=("key",),
                name="uniq_library_key_when_no_workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryrevision",
            constraint=models.UniqueConstraint(
                fields=("library", "version"), name="uniq_library_revision_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="scriptlibrary",
            constraint=models.UniqueConstraint(
                fields=("script", "library"), name="uniq_script_library"
            ),
        ),
    ]
