# Generated by Django 6.0.1 on 2026-07-17 06:33
#
# Promotes the single `GlobalSettings.s3_*` connection block into StorageConnection
# rows (many). The pre-existing config becomes exactly one row flagged `is_default`,
# which is the row backups resolve — so an upgrade changes nothing about backups.
#
# Operation order is load-bearing: create the table, then COPY the old fields into
# it, and only then drop them. Django's autodetector emits the removals first; they
# were moved after the RunPython by hand.

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_s3_config_to_connection(apps, schema_editor):
    """Copy the legacy single S3 config into one default StorageConnection row.

    Ciphertext columns are copied VERBATIM — never decrypt/re-encrypt here. The
    encryption key is env-provided, so touching EncryptionService would make this
    migration fail on any deploy where the key isn't loaded yet.
    """
    GlobalSettings = apps.get_model("core", "GlobalSettings")
    StorageConnection = apps.get_model("core", "StorageConnection")

    settings = GlobalSettings.objects.first()
    if settings is None or not settings.s3_bucket_name:
        # Never configured — nothing to carry forward.
        return

    # Infer the provider so the Services card shows a sensible type. Cosmetic:
    # every type builds the same boto3 client from the stored fields.
    endpoint = (settings.s3_endpoint_url or "").lower()
    if "r2.cloudflarestorage.com" in endpoint:
        provider_type = "r2"
    elif "backblazeb2.com" in endpoint:
        provider_type = "b2"
    elif "digitaloceanspaces.com" in endpoint:
        provider_type = "spaces"
    elif not endpoint:
        provider_type = "s3"
    else:
        provider_type = "custom"

    connection = StorageConnection.objects.create(
        provider_type=provider_type,
        name="Default",
        endpoint_url=settings.s3_endpoint_url or "",
        region=settings.s3_region or "us-east-1",
        bucket=settings.s3_bucket_name,
        access_key_encrypted=settings.s3_access_key_encrypted or "",
        secret_key_encrypted=settings.s3_secret_key_encrypted or "",
        use_ssl=settings.s3_use_ssl,
        path_style=settings.s3_path_style,
        public_base_url="",
        is_default=True,
        # `s3_enabled` was the "configured but switched off" flag the backup
        # scheduler gates on. Dropping it here would silently resume backups on
        # an instance that had deliberately paused them.
        enabled=settings.s3_enabled,
        last_tested_at=settings.s3_last_tested_at,
    )

    # NOT wired to assets_storage on purpose: the backup bucket is private, and
    # auto-selecting it would let plugin objects land in it. The operator picks an
    # assets connection explicitly; until then the seam reports unavailable.
    del connection


def restore_s3_config_from_connection(apps, schema_editor):
    """Reverse: copy the default row's fields back onto GlobalSettings."""
    GlobalSettings = apps.get_model("core", "GlobalSettings")
    StorageConnection = apps.get_model("core", "StorageConnection")

    settings = GlobalSettings.objects.first()
    connection = StorageConnection.objects.filter(is_default=True).first()
    if settings is None or connection is None:
        return

    settings.s3_endpoint_url = connection.endpoint_url
    settings.s3_region = connection.region
    settings.s3_bucket_name = connection.bucket
    settings.s3_access_key_encrypted = connection.access_key_encrypted
    settings.s3_secret_key_encrypted = connection.secret_key_encrypted
    settings.s3_use_ssl = connection.use_ssl
    settings.s3_path_style = connection.path_style
    settings.s3_enabled = connection.enabled
    settings.s3_last_tested_at = connection.last_tested_at
    settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_script_libraries"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("r2", "Cloudflare R2"),
                            ("s3", "AWS S3"),
                            ("b2", "Backblaze B2"),
                            ("spaces", "DigitalOcean Spaces"),
                            ("minio", "MinIO / self-hosted"),
                            ("custom", "Custom S3-compatible"),
                        ],
                        default="custom",
                        help_text="Which S3-compatible backend this connection talks to",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'Backups (R2)' or 'Public assets'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "endpoint_url",
                    models.CharField(
                        blank=True,
                        help_text="S3 endpoint URL (leave empty for AWS S3)",
                        max_length=500,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        default="us-east-1",
                        help_text="S3 region ('auto' for R2)",
                        max_length=50,
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        blank=True, help_text="Bucket name", max_length=255
                    ),
                ),
                (
                    "access_key_encrypted",
                    models.TextField(blank=True, help_text="Access key ID (encrypted)"),
                ),
                (
                    "secret_key_encrypted",
                    models.TextField(
                        blank=True, help_text="Secret access key (encrypted)"
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        default=True, help_text="Use SSL/TLS for connections"
                    ),
                ),
                (
                    "path_style",
                    models.BooleanField(
                        default=False,
                        help_text="Use path-style addressing (required for MinIO)",
                    ),
                ),
                (
                    "public_base_url",
                    models.CharField(
                        blank=True,
                        help_text="Public base URL for hot-linkable objects, e.g. an R2 public domain. Blank = objects are served via presigned URLs that EXPIRE.",
                        max_length=500,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The connection backups use. Exactly one row carries this.",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Switch off without losing the configuration",
                    ),
                ),
                (
                    "last_tested_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this connection last tested successfully",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "storage connection",
                "verbose_name_plural": "storage connections",
                "db_table": "storage_connections",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="assets_storage",
            field=models.ForeignKey(
                blank=True,
                help_text="Connection plugins read and write through StorageAPI. Blank = the storage seam is unavailable (fails closed). Deliberately does NOT fall back to the backup default — that would put plugin objects in the backup bucket.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.storageconnection",
            ),
        ),
        # Must sit between the schema additions and the removals: it reads the very
        # fields the RemoveFields below drop.
        migrations.RunPython(
            migrate_s3_config_to_connection,
            restore_s3_config_from_connection,
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="s3_access_key_encrypted",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="s3_bucket_name",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="s3_enabled",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="s3_endpoint_url",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="s3_last_tested_at",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="s3_path_style",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="s3_region",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="s3_secret_key_encrypted",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="s3_use_ssl",
        ),
    ]
