# Generated by Django 6.0.8 on 2026-09-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_storage_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptschedule',
            name='cron_expression',
            field=models.CharField(blank=True, default='', help_text='Raw cron expression, e.g. "0 9 * * 1-5" (minute hour day-of-month month day-of-week)', max_length=100),
        ),
        migrations.AlterField(
            model_name='scriptschedule',
            name='run_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('interval', 'Interval'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('cron', 'Cron expression')], default='manual', max_length=20),
        ),
    ]
