# Generated by Django 6.0.8 on 2026-09-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_schedule_cron_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptschedule',
            name='yearly_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month for yearly mode (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='scriptschedule',
            name='yearly_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month for yearly mode (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='scriptschedule',
            name='yearly_time',
            field=models.CharField(blank=True, default='', help_text='Time for yearly mode (HH:MM)', max_length=5),
        ),
        migrations.AlterField(
            model_name='scriptschedule',
            name='run_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('interval', 'Interval'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('cron', 'Cron expression'), ('yearly', 'Yearly')], default='manual', max_length=20),
        ),
    ]
