"""
Django settings for pyrunner project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-2-^q2i(5y%jt8&-4u1*ve$%2efq568qi&dn0f)fl%uzkru5lm4",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party
    "django_q",
    "tailwind",
    "theme",
    # Local apps
    "core",
]

# Tailwind CSS
TAILWIND_APP_NAME = "theme"
INTERNAL_IPS = ["127.0.0.1"]
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "pyrunner.middleware.NoCacheMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.SetupWizardMiddleware",
]

ROOT_URLCONF = "pyrunner.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.pyrunner_version",
            ],
        },
    },
]

WSGI_APPLICATION = "pyrunner.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "data" / "db.sqlite3",
    }
}


# Custom User Model
AUTH_USER_MODEL = "core.User"

# Auth URLs
LOGIN_URL = "auth:login"
LOGIN_REDIRECT_URL = "cpanel:dashboard"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise for serving static files in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email Configuration
# Console backend for development, configure SMTP in production
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@pyrunner.local")

# Resend API Configuration (Production)
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
USE_RESEND = os.environ.get("USE_RESEND", "False").lower() == "true"


# django-q2 Configuration
def _get_q_cluster_config():
    """
    Get Q_CLUSTER configuration from database with environment fallbacks.

    This is called at module load time. Database values take precedence
    over environment variables when available.
    """
    # Default values (from env vars or hardcoded defaults)
    config = {
        "name": "PyRunner",
        "workers": int(os.environ.get("Q_WORKERS", 2)),
        "timeout": 600 if os.name != "nt" else 0,
        "retry": 660,
        "queue_limit": 20,
        "bulk": 5,
        "orm": "default",
        "catch_up": False,
    }

    # Try to load from database
    try:
        from django.db import connection
        from django.db.utils import OperationalError, ProgrammingError

        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT q_workers, q_timeout, q_retry, q_queue_limit "
                "FROM global_settings WHERE id = 1"
            )
            row = cursor.fetchone()
            if row:
                config["workers"] = row[0] or config["workers"]
                # On Windows, force timeout to 0 regardless of DB value
                if os.name == "nt":
                    config["timeout"] = 0
                else:
                    config["timeout"] = row[1] if row[1] is not None else config["timeout"]
                config["retry"] = row[2] or config["retry"]
                config["queue_limit"] = row[3] or config["queue_limit"]
    except (OperationalError, ProgrammingError, Exception):
        # Database not ready yet (migrations not run), use defaults
        pass

    return config


Q_CLUSTER = _get_q_cluster_config()


# PyRunner Configuration
DATA_DIR = BASE_DIR / "data"
ENVIRONMENTS_ROOT = DATA_DIR / "environments"
SCRIPTS_WORKDIR = DATA_DIR / "workdir"

# Ensure directories exist
DATA_DIR.mkdir(exist_ok=True)
ENVIRONMENTS_ROOT.mkdir(exist_ok=True)
SCRIPTS_WORKDIR.mkdir(exist_ok=True)


# Secrets Encryption
# Generate a key with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
ENCRYPTION_KEY = os.environ.get("ENCRYPTION_KEY", "")
